Fix a bug about show a forum list
When a user visit a forum that he never visit,
he will get a 500 error because a AttributeError:

File "./flaskbb/forum/models.py", line 344, in first_unread
  filter(Post.date_created > topicsread.last_read).\
      AttributeError: 'NoneType' object has no attribute 'last_read'